# Generated by Django 6.1 on 2026-08-25 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_followrequest'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='followrequest',
            index=models.Index(fields=['receiver', 'status'], name='users_follo_receive_aabaaf_idx'),
        ),
        migrations.AddIndex(
            model_name='followrequest',
            index=models.Index(fields=['sender', 'status'], name='users_follo_sender__7d10bb_idx'),
        ),
    ]
