# Generated by Django 6.1 on 2026-08-25 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_followrequest_users_follo_receive_aabaaf_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followrequest',
            old_name='updateda_at',
            new_name='updated_at',
        ),
    ]
