# Generated by Django 6.1 on 2026-08-30 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('posts', '0004_reply'),
        ('users', '0007_rename_updateda_at_followrequest_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('FOLLOW', 'Follow'), ('FOLLOW_REQUEST', 'Follow Request'), ('FOLLOW_ACCEPTED', 'Follow Accepted'), ('LIKE', 'Like'), ('COMMENT', 'Comment'), ('REPLY', 'Reply')], max_length=30)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='notifications',
            name='notificatio_recipie_526734_idx',
        ),
        migrations.RemoveIndex(
            model_name='notifications',
            name='notificatio_recipie_c103b4_idx',
        ),
        migrations.AddField(
            model_name='notification',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='posts.comment'),
        ),
        migrations.AddField(
            model_name='notification',
            name='follow_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='users.followrequest'),
        ),
        migrations.AddField(
            model_name='notification',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='posts.post'),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='posts.reply'),
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='follow_request',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='post',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='recipient',
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'created_at'], name='notificatio_recipie_f39341_idx'),
        ),
        migrations.DeleteModel(
            name='Notifications',
        ),
    ]
